config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
  resources :subtasks
  end
  #creates all 7 routes for you
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
    belongs_to :task
    
end

app/models/task.rb
class Task < ApplicationRecord
    #relationship
has_many :subtasks

    validates :title, :description, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
    before_action :set_task

    def new
     @subtask = @task.subtasks.new 
    end
    
    def set_task
        @task = Task.find (params[:task_id])
    end 

    def create
        @subtask = @task.subtasks.new(subtask_params)
        if @subtask.save
            redirect_to task_path(@task)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @subtask = @task.subtasks.find(params[:task_id])
    end

    def update
        if @subtask = @task.subtasks.update(subtask_params)
            redirect_to task_path(@task)
        else 
            render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        if @task.destroy
            redirect_to root_path
        else
            "BYEBYE SUBTASK"
        end
    end

    def subtask_params
        params.required(:subtask).permit(:user_story, :story_points, :status, :task_id)
    end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy] #step 1

    def index
        @tasks = Task.all
        @test = "THIS IS A TEST"
    end
    #everyth must be in the class
    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            redirect_to task_path(@task)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @task = Task.find(params[ :id])
    end

    def edit
        @task = Task.find(params[ :id])
    end

    def update
        if @task.update(task_params)
            redirect_to task_path(@task)
        else 
            render :edit, status: :unprocessable_entity
        end

    end

    def destroy
        if @task.destroy
            redirect_to root_path
        else
            "BYE BYE WORK"
        end
    end

    private
    def set_task #step 2
        @task = Task.find(params[:id])
    end

    def task_params
        params.required(:task).permit(:title, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subtasks/_form.html.erb
<%= simple_form_for [@task, @subtask] do |t| %>
    <%= t.input :user_story %>
    <%= t.input :story_points, as: :float %>
    <%= t.input :status, collection: ["Pending", "In Development", "Completed"] %>
    <%= t.button :submit %>

    <% end %>

app/views/subtasks/edit.html.erb
Edit Page

<%= render partial: 'subtasks/form'%>

app/views/subtasks/new.html.erb
<h1> Add a New Subtask</h1>
<%= simple_form_for [@task, @subtask] do |t| %>
    <%= t.input :user_story %>
    <%= t.input :story_points, as: :float %>
    <%= t.input :status, collection: ["Pending", "In Development", "Completed"] %>
    <%= t.button :submit %>

    <% end %>
  

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
Edit Page

<%= render partial: 'tasks/form'%>

app/views/tasks/index.html.erb
<h1>Hello World</h1>
<%# this page should show all tasks %>
<%= @test %>
<% @test %>

<%= link_to 'Click here to create new task', new_task_path %>


<table>
    <thead>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Edit</th>
         <th>Delete</th>
    </thead>
    <tbody>
    <% @tasks.each do |task| %>
        <tr>
            <th><%= task.id %></th>
            <th><%= link_to task.title, task_path(task) %></th>
            <th><%= task.description %></th>
            <th><%= link_to "edit", edit_task_path(task)%></th>
            <th><%= button_to "delete", task_path(task), method: :delete %></th>
        </tr>
    <% end %>
    </tbody>
</table>
<h2>Total Record: <%= @tasks.count %> </h2>

app/views/tasks/new.html.erb
<h1> Add a New Task</h1>
<%= simple_form_for @task do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.button :submit %>
    
    <% end %>

app/views/tasks/show.html.erb
<h1>SHOW OFF</h1>
<h2>FISHBALL SHOW PAGE</h2>
<h2><%= @task.title %></h2>
<h3><%= @task.description %></h3>
<h4><%= link_to 'index page', tasks_path%></h4>
<h3><%=  %>
<%= link_to "Add sub_task", new_task_subtask_path(@task) %>

<table>
    <thead>
     <th>#</th>
     <th> User Story</th>
     <th> Story Point</th>
     <th> Status</th>
    </thead>
    <tbody>
        <%@task.subtasks.each do |task| %>
        <tr>
        <td><%= task.id%></td>
        <td><%= task.user_story%></td>
        <td><%= task.story_points%></td>
        <td><%= task.status%></td>
        <td><%= link_to "Edit", edit_task_subtask_path(@task) %></td>
        <td><%= button_to "Delete", task_subtask_path(@task), method: :delete%></td>
    </tr>
    <%end%>
    </tbody>
    </table>